apiVersion: v1
kind: Secret
metadata:
  name: bankapp-secrets
  namespace: bankapp
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: bankdb
  MYSQL_USER: bankuser
  MYSQL_PASSWORD: bankpass
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.bankapp.svc.cluster.local:3306/bankdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  SPRING_DATASOURCE_USERNAME: bankuser
  SPRING_DATASOURCE_PASSWORD: bankpass
