apiVersion: v1
kind: Secret
metadata:
  name: bankapp-secrets
  namespace: bankapp
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: bankdb
  MYSQL_USER: bankuser
  MYSQL_PASSWORD: bankpass
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_NAME: bankdb
  DB_USER: bankuser
  DB_PASSWORD: bankpass
